version: 7.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)
environment:
  dummy_secret:
    secure: iToG2vv7gSS8XVLRA/F4yxhjk6RIYzHFvusybuKxRQ2N7DdAIFkqlBQG1yfkqAGD
before_build:
- cmd: >-
    cd src

    nuget restore

    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt dummy.data -out NFETeam.snk -secret "%dummy_secret%"
build:
  verbosity: minimal
after_build:
- cmd: cd %APPVEYOR_BUILD_FOLDER%\src\out\
- cmd: del /q *.pdb, *.xml
artifacts:
- path: src\out
  name: NFE-Tools-v$(appveyor_build_version)
