#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NToolboxAndroid.Resource", IsApplication=true)]

namespace NToolboxAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ntoolbox_android = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int deviceName = 2131034114;
			
			// aapt resource value: 0x7f050015
			public const int download = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int imageView1 = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int layoutPreheatCurve = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int layoutPreheatPower = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int layoutTempControl = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int power = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int preheatDelay = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int preheatPower = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int preheatPowerType = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int preheatTime = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int profileName = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int resistance = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int resistanceLocked = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int scrollView1 = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int spinnerMaterial = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int spinnerMode = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int spinnerPreheat = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int spinnerPreheatCurve = 2131034119;
			
			// aapt resource value: 0x7f050014
			public const int tempDominant = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int temperatur = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int temperaturType = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int upload = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
